# ------------------------------------------------------- #
# Note: this file originates in action-composite-template #
# ------------------------------------------------------- #

version: 2
updates: []
